import contextlib as contextlib
import os as os
import shutil as shutil
import subprocess as subprocess
import tempfile as tempfile
import threading as threading
import time as time
from dataclasses import dataclass as dataclass
from dataclasses import field as field
from dataclasses import replace as replace
from pathlib import Path as Path
from typing import TYPE_CHECKING as TYPE_CHECKING
from typing import Any as Any

from torrcast import InfraError as InfraError
from torrcast.profile import CAUTIOUS as CAUTIOUS
from torrcast.stream_core import _TIMEOUT as _TIMEOUT
from torrcast.stream_core import PACK_PENDING_BYTES as PACK_PENDING_BYTES
from torrcast.stream_pack import Grid
from torrcast.timing import mark as mark

__all__ = [
    "CAUTIOUS",
    "PACK_PENDING_BYTES",
    "TYPE_CHECKING",
    "_TIMEOUT",
    "Any",
    "Feed",
    "InfraError",
    "Packer",
    "Path",
    "_names",
    "_paths",
    "contextlib",
    "dataclass",
    "field",
    "mark",
    "merge_tracks",
    "os",
    "replace",
    "shutil",
    "subprocess",
    "tempfile",
    "threading",
    "time",
    "timeline_shift",
]

@dataclass(slots=True)
class Packer:
    proc: subprocess.Popen[bytes]
    out: Path
    run: Path
    first: int = ...
    edge: int = ...
    log: Any = ...
    publish_lock: Any = field(default_factory=threading.Lock)
    halted: bool = ...
    stopped: str = ...
    blamed: bool = ...
    spare: Path | None = ...
    told: Any = ...
    last: int = ...
    began: float = ...
    at: float = ...
    rate: float = ...
    burst: float = ...
    grid: Grid | None = ...
    whole: bool | None = ...
    hold: Any = ...
    shrink: Any = ...
    cap: int = ...
    def __post_init__(self) -> None: ...
    @classmethod
    def start(
        cls,
        command: list[str],
        out: Path,
        run: Path,
        first: int = 0,
        spare: Path | None = None,
        told: Any = None,
        hold: Any = None,
        shrink: Any = None,
        last: int = -1,
        at: float = 0.0,
        rate: float = 0.0,
        burst: float = 0.0,
        grid: Grid | None = None,
        cap: int = ...,
    ) -> Packer: ...
    def eta(self, film: float) -> float: ...
    def finished(self) -> bool: ...
    def _reached(self) -> bool: ...
    def publish(self) -> None: ...
    def _publish(self) -> None: ...
    def cuts(self) -> list[tuple[int, float, float]]: ...
    def drift(self, grid: Grid) -> float: ...
    def pending(self) -> int: ...
    def frontier(self) -> int: ...
    def halt(self, reason: str = "пауза на пульте") -> None: ...
    def poll(self) -> int | None: ...
    def why(self) -> str: ...
    def stop(self, keep_files: bool = False, reason: str = "") -> None: ...

def timeline_shift(copy: Path, recode: Path, timeout: float = ...) -> float | None: ...
def merge_tracks(
    video: Path, audio: Path, dst: Path, timeout: float = ..., shift: float = 0.0
) -> bool: ...
def _names(out: Path) -> list[str]: ...
def _paths(out: Path) -> list[Path]: ...

@dataclass(slots=True)
class Feed:
    source: str
    audio: int
    out: Path
    grid: Grid
    readrate: float = ...
    burst: float = ...
    keep: float = ...
    ahead: int = ...
    jump: float = ...
    wait: float = ...
    cap: int = ...
    pending_cap: int = ...
    limit: int = ...
    packer: Packer | None = ...
    lock: Any = field(default_factory=threading.Lock)
    restarted: float = ...
    crashes: int = ...
    fatal: str = ...
    log: Any = ...
    recoder: Any = ...
    encode: Any = ...
    vault: Any = ...
    moved: float = field(default_factory=time.monotonic)
    offline: str = ...
    skipped: set[int] = field(default_factory=set)
    shrink_lock: Any = field(default_factory=threading.Lock)
    @property
    def duration(self) -> float: ...
    def manifest(self) -> bytes: ...
    def segment(self, slot: int) -> Path | None: ...
    def _warm(self, slot: int) -> Path | None: ...
    def have(self, slot: int) -> bool: ...
    def _steer(self, slot: int) -> bool: ...
    def _mute(self) -> None: ...
    def _survive(self, packer: Packer) -> bool: ...
    def restart(self, slot: int) -> None: ...
    def _shrink(self, slot: int, size: int = 0) -> bool: ...
    def _skip(self, slot: int, size: int, reason: str) -> bool: ...
    def sweep(self) -> None: ...
    def prune(self, played: float) -> None: ...
    def front(self, played: float = 0.0) -> float: ...
    def drift(self) -> float: ...
    def weight(self) -> int: ...
    def trouble(self) -> str: ...
    def stall(self, why_source: str) -> None: ...
    def halted(self) -> bool: ...
    def rest(self) -> bool: ...
    def halt(self) -> None: ...
    def stop(self) -> None: ...
    def _say(self, text: str) -> None: ...
