from dataclasses import dataclass

from torrcast.cast import Receiver as Receiver
from torrcast.commands import Watch as Watch
from torrcast.profile import Profile as Profile
from torrcast.stream import Feed as Feed
from torrcast.stream import Supply as Supply
from torrcast.timing import Clock as Clock
from torrcast.warm import Warmer as Warmer

__all__: list[str]
TAIL_LIMIT: float

@dataclass(slots=True)
class _Revival:
    since: float = ...
    began: float = ...
    why: str = ...
    tries: int = ...
    last: float = ...
    warmed: float = ...
    supply: Supply | None = ...
    blamed: bool = ...
    dropped: bool = ...
    back: float = ...
    pause: float = ...
    drop: float = ...
    ended: bool = ...
    lived: float = ...
    clock: Clock = ...
    def alive(self, shown: bool = True) -> None: ...
    def darkness(self) -> float: ...
    def resurrect(
        self, receiver: Receiver, feed: Feed, warmer: Warmer | None, pos: float, shown: bool = True
    ) -> bool: ...
    def _why(self, feed: Feed) -> str: ...
    def _may(self, feed: Feed, warmer: Warmer | None, pos: float) -> bool: ...

def _hold(
    receiver: Receiver,
    feed: Feed,
    watch: Watch | None = None,
    warmer: Warmer | None = None,
    supply: Supply | None = None,
    profile: Profile = ...,
    clock: Clock = ...,
    session_tag: str = "",
    start: float = 0.0,
    raised: bool = True,
) -> bool: ...
