import time as time
from dataclasses import dataclass as dataclass
from dataclasses import field as field

from torrcast.adapters.filesystem.state import State as State
from torrcast.domain.entry import Entry as Entry

__all__ = ["WATCH_SECONDS", "Entry", "State", "Watch", "dataclass", "field", "time"]

WATCH_SECONDS: float

@dataclass(slots=True)
class Watch:
    key: str
    entry: Entry
    every: float = ...
    done: bool = ...
    sealed: bool = ...
    seen: bool = ...
    last: float = ...
    def see(self, pos: float) -> None: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
