"""Часть CLI; публичный фасад — :mod:`torrcast.cli`.

Реэкспорт правил ранжирования: ворота отбора, порядок меню, счёт отсева и строки про
звук. Ни строчки логики - каждая единица живёт в своём файле пакета.
"""

from __future__ import annotations

from torrcast.domain.audio_track import AudioTrack as AudioTrack
from torrcast.domain.bitrate_mbit import bitrate_mbit as bitrate_mbit
from torrcast.domain.episode import Episode as Episode
from torrcast.domain.infra_error import InfraError as InfraError
from torrcast.domain.media import Media as Media
from torrcast.domain.not_found_error import NotFoundError as NotFoundError
from torrcast.domain.rank_settings import ALIVE_SEEDERS as ALIVE_SEEDERS
from torrcast.domain.rank_settings import DISC_RE as DISC_RE
from torrcast.domain.rank_settings import EXTRAS_MBIT as EXTRAS_MBIT
from torrcast.domain.rank_settings import FULL_HD_LIVENESS as FULL_HD_LIVENESS
from torrcast.domain.rank_settings import FULL_HEIGHT as FULL_HEIGHT
from torrcast.domain.rank_settings import GATE_LIVENESS as GATE_LIVENESS
from torrcast.domain.rank_settings import HD_HEIGHT as HD_HEIGHT
from torrcast.domain.rank_settings import HONEST_RATIO as HONEST_RATIO
from torrcast.domain.rank_settings import PEER_GRACE as PEER_GRACE
from torrcast.domain.rank_settings import SD_BITRATE as SD_BITRATE
from torrcast.domain.rank_settings import SEASON_EPISODES as SEASON_EPISODES
from torrcast.domain.rank_settings import SOUND_LIVENESS as SOUND_LIVENESS
from torrcast.domain.rank_settings import STEP_GRACE as STEP_GRACE
from torrcast.domain.rank_settings import TABLE_LIMIT as TABLE_LIMIT
from torrcast.domain.rank_settings import VOICE_MENU as VOICE_MENU
from torrcast.domain.recode_settings import RECODE_HEIGHT as RECODE_HEIGHT
from torrcast.domain.release import Release as Release
from torrcast.domain.torr_file import TorrFile as TorrFile
from torrcast.ports.console import Console as Console
from torrcast.usecases.choice.warned import warned as warned
from torrcast.usecases.rank._cut import _cut as _cut
from torrcast.usecases.rank._gb import _gb as _gb
from torrcast.usecases.rank._hms import _hms as _hms
from torrcast.usecases.rank.ask import ask as ask
from torrcast.usecases.rank.bitrate_of import bitrate_of as bitrate_of
from torrcast.usecases.rank.configure import configure as configure
from torrcast.usecases.rank.default_unnamed import default_unnamed as default_unnamed
from torrcast.usecases.rank.drop_reason import drop_reason as drop_reason
from torrcast.usecases.rank.drop_reasons import _CODEC as _CODEC
from torrcast.usecases.rank.drop_reasons import _DISC as _DISC
from torrcast.usecases.rank.drop_reasons import _EXTRAS as _EXTRAS
from torrcast.usecases.rank.drop_reasons import _HEAVY as _HEAVY
from torrcast.usecases.rank.drop_reasons import _HEVC as _HEVC
from torrcast.usecases.rank.drop_reasons import _NO_EPISODE as _NO_EPISODE
from torrcast.usecases.rank.drop_reasons import _PINNED as _PINNED
from torrcast.usecases.rank.drop_reasons import _QUIET as _QUIET
from torrcast.usecases.rank.drop_reasons import _SMALL as _SMALL
from torrcast.usecases.rank.drop_reasons import _SOURCE as _SOURCE
from torrcast.usecases.rank.drop_reasons import OFF_SEASON as OFF_SEASON
from torrcast.usecases.rank.gate_open import gate_open as gate_open
from torrcast.usecases.rank.heard import heard as heard
from torrcast.usecases.rank.hevc_hope import hevc_hope as hevc_hope
from torrcast.usecases.rank.honest_shot import honest_shot as honest_shot
from torrcast.usecases.rank.is_candidate import is_candidate as is_candidate
from torrcast.usecases.rank.is_dated import is_dated as is_dated
from torrcast.usecases.rank.is_dead import is_dead as is_dead
from torrcast.usecases.rank.is_disc import is_disc as is_disc
from torrcast.usecases.rank.is_extra import is_extra as is_extra
from torrcast.usecases.rank.is_full_hd import is_full_hd as is_full_hd
from torrcast.usecases.rank.last_hope import last_hope as last_hope
from torrcast.usecases.rank.misses_episode import misses_episode as misses_episode
from torrcast.usecases.rank.needs_whole_recode import needs_whole_recode as needs_whole_recode
from torrcast.usecases.rank.over_ceiling import over_ceiling as over_ceiling
from torrcast.usecases.rank.pack_mbit import pack_mbit as pack_mbit
from torrcast.usecases.rank.peer_grace import peer_grace as peer_grace
from torrcast.usecases.rank.pick_voice import pick_voice as pick_voice
from torrcast.usecases.rank.promises_more import promises_more as promises_more
from torrcast.usecases.rank.quality_text import quality_text as quality_text
from torrcast.usecases.rank.queue_drops import queue_drops as queue_drops
from torrcast.usecases.rank.rank_releases import rank_releases as rank_releases
from torrcast.usecases.rank.render_table import render_table as render_table
from torrcast.usecases.rank.sound_note import sound_note as sound_note
from torrcast.usecases.rank.sound_step import sound_step as sound_step
from torrcast.usecases.rank.spoken import spoken as spoken
from torrcast.usecases.rank.stepdown_note import STEP_RATIO as STEP_RATIO
from torrcast.usecases.rank.stepdown_note import stepdown_note as stepdown_note
from torrcast.usecases.rank.understated import understated as understated
from torrcast.usecases.rank.voice_note import voice_note as voice_note
from torrcast.usecases.rank.voice_unproven import voice_unproven as voice_unproven
from torrcast.usecases.rank.voices_table import voices_table as voices_table
