"""Сетка сегментов в объёме, который нужен прогреву."""

from collections.abc import Callable
from typing import Protocol


class WarmGrid(Protocol):
    """Границы кусков фильма: где начинается кусок, где кончается и сколько весит."""

    @property
    def count(self) -> int: ...
    @property
    def duration(self) -> float: ...
    @property
    def origin(self) -> float: ...
    @property
    def on_keys(self) -> bool: ...
    @property
    def weigh(self) -> Callable[[float, float], float] | None: ...

    def start(self, slot: int) -> float: ...
    def end(self, slot: int) -> float: ...
    def span(self, slot: int) -> float: ...
