"""Внешние решения и ввод-вывод сценария выбора."""

from typing import Protocol, TypeVar

from torrcast.domain.config import Config
from torrcast.domain.facts.fact import Fact
from torrcast.domain.facts.origin import Origin
from torrcast.domain.profile import Profile
from torrcast.domain.release import Release
from torrcast.ports.choice_environment.choice_args import ChoiceArgs
from torrcast.ports.choice_environment.choice_facts import ChoiceFacts
from torrcast.ports.menu_paint import MenuPaint

#: План показа: окружение его не читает, а отдаёт обратно ТОТ ЖЕ вид, что получило.
#: Сам план объявлен слоем сценариев, и назвать его порту нечем - зато переменной типа
#: договор говорит главное: пересборка плана меняет числа внутри, а не род значения.
_PlanT = TypeVar("_PlanT")


class ChoiceEnvironment(Protocol):
    """Всё, что выбор получает от композиционного корня."""

    @property
    def alive_seeders(self) -> int: ...
    @property
    def ctl_env(self) -> str: ...
    @property
    def not_found_error(self) -> type[Exception]: ...

    def read_command(self) -> str | None: ...
    def write(self, line: str) -> None: ...
    def stdin_is_tty(self) -> bool: ...
    def ask(self, question: str, count: int, default: int | None = 1) -> int: ...
    def menu(self) -> MenuPaint: ...
    def columns(self) -> int: ...
    def fact(self) -> Fact: ...
    def empty_origin(self) -> Origin: ...
    def origin(self, title: str, series: bool) -> Origin: ...
    def shorten(self, text: str) -> str: ...
    def emit(self, event: str, action: str, **facts: object) -> None: ...
    def cut(self, text: str, limit: int) -> str: ...
    def bitrate_of(self, release: Release, duration: float) -> float | None: ...
    def hevc_hope(self, release: Release, last: bool) -> bool: ...
    def is_candidate(
        self,
        release: Release,
        runtime: float,
        warn_mbit: float,
        loose: bool = False,
        hard_mbit: float = 0.0,
        last: bool = False,
        copy_hevc: bool = False,
    ) -> bool: ...
    def is_dated(self, release: Release, runtime: float) -> bool: ...
    def timed(
        self,
        plan: _PlanT,
        facts: ChoiceFacts | None,
        args: ChoiceArgs,
        config: Config,
        profile: Profile,
    ) -> _PlanT: ...
