"""Совместимый фасад поиска для старых импортов."""

# mypy: ignore-errors
import sys

from torrcast import trace as trace
from torrcast.usecases import discover as _discovery_impl
from torrcast.usecases.discover import (
    CAUTIOUS,
    CIRCLE_SHARE,
    FACTS_BUDGET,
    GOAL,
    KIN_SHOWN,
    SECOND_LEAST,
    Config,
    Episode,
    InfraError,
    NotFoundError,
    Origin,
    Picture,
    Profile,
    Progress,
    Release,
    _ask,
    _asked_kind,
    _kin,
    _no_budget,
    _nothing,
    _query_note,
    _search,
    _second_language,
    _vouched,
    kin_line,
    menu_order,
    other_words,
    replace,
    same_name,
    season_gaps,
    silent_swarm,
    slugify,
    split_franchise_index,
    transliterate,
    unfit_line,
    unfit_pool,
    worth_asking_original,
)

__all__ = [
    "CAUTIOUS",
    "CIRCLE_SHARE",
    "FACTS_BUDGET",
    "GOAL",
    "KIN_SHOWN",
    "SECOND_LEAST",
    "Config",
    "Episode",
    "InfraError",
    "NotFoundError",
    "Origin",
    "Picture",
    "Profile",
    "Progress",
    "Release",
    "_ask",
    "_asked_kind",
    "_kin",
    "_no_budget",
    "_nothing",
    "_query_note",
    "_search",
    "_second_language",
    "_vouched",
    "kin_line",
    "menu_order",
    "other_words",
    "replace",
    "same_name",
    "season_gaps",
    "silent_swarm",
    "slugify",
    "split_franchise_index",
    "trace",
    "transliterate",
    "unfit_line",
    "unfit_pool",
    "worth_asking_original",
]

sys.modules[__name__] = _discovery_impl
