"""Совместимый фасад справки о картинах."""

from __future__ import annotations

# Статический список нужен mypy для реэкспортов; внизу сохраняется runtime-список.
__all__ = [
    "BLURB_CAP",
    "CACHE_PATH",
    "EMPTY_TTL",
    "FACTS_BUDGET",
    "HTTP_TIMEOUT",
    "RATINGS_PATH",
    "RU_NAMES_PATH",
    "SOURCE_JOIN",
    "SOURCE_MAP",
    "SOURCE_WIKI",
    "SOURCE_WIKIDATA",
    "TOPUP_LIMIT",
    "TYPE_CHECKING",
    "USER_AGENT",
    "_ABBREV",
    "_CINEMA_RE",
    "_CJK",
    "_CYRILLIC",
    "_DEFAULT_CACHE_PATH",
    "_EXCHARS",
    "_EXLIMIT",
    "_FILM_WORD_RE",
    "_GENRE_RE",
    "_HATNOTE_RE",
    "_LAST_WORD_RE",
    "_MADE_RE",
    "_NEAR_LETTERS",
    "_ODD_WEIGHT",
    "_ORIGINAL_RE",
    "_PHRASE_WORDS",
    "_QUALIFIERS",
    "_RESOLVED",
    "_RESOLVE_LOCK",
    "_RESOLVE_TTL",
    "_RUNTIME_RE",
    "_RU_LOCK",
    "_RU_NAMES",
    "_SCREEN_RE",
    "_SEARCH_HITS",
    "_SENTENCE_START_RE",
    "_SERIES_WORD_RE",
    "_SUGGEST_HITS",
    "_TAIL_RE",
    "_TITLED_RE",
    "_TV_KINDS",
    "_VOTES",
    "_WIKIDATA_HOST",
    "_WIKIDATA_PATH",
    "_WIKI_HOST",
    "_WIKI_PATH",
    "_WORK_RE",
    "_YEAR_RE",
    "Fact",
    "Facts",
    "Final",
    "Origin",
    "Path",
    "_IPv4Connection",
    "_RuName",
    "_about_cinema",
    "_article",
    "_asked_otherwise",
    "_by_phrase",
    "_cache_path",
    "_cached",
    "_cached_origin",
    "_catalogued",
    "_crowded",
    "_digit_edit",
    "_ends_phrase",
    "_extract_params",
    "_fits_type",
    "_imdb_ru",
    "_key",
    "_localized_short_name",
    "_misremembered",
    "_near_name",
    "_one_edit",
    "_origin_key",
    "_origin_typed",
    "_other_part",
    "_outweighed",
    "_own_name_first",
    "_pages",
    "_ranked",
    "_read_cache",
    "_read_pages",
    "_read_ru_names",
    "_remember",
    "_remember_origin",
    "_resolve",
    "_ru_names",
    "_same_latin",
    "_same_picture_origin",
    "_search_params",
    "_second_source_year",
    "_suggested",
    "_votes",
    "_write_cache",
    "akin",
    "confirmed_year",
    "confirms",
    "contextlib",
    "dataclass",
    "english_title",
    "fetch",
    "get_json",
    "hms",
    "http",
    "json",
    "latin_title",
    "minutes_of",
    "namesake",
    "origin",
    "origin_either",
    "origin_now",
    "os",
    "picture_year",
    "published_year",
    "ratings",
    "re",
    "read_origin",
    "read_published",
    "read_sparql",
    "redirected_name",
    "same_name",
    "same_word",
    "same_words",
    "sentence",
    "shorten",
    "slugify",
    "socket",
    "sourced",
    "split_franchise_index",
    "ssl",
    "state_path",
    "threading",
    "time",
    "titles_for",
    "transliterate",
    "urlencode",
    "wiki_extracts",
    "wikidata_ids",
    "with_source",
    "without_source",
]

import sys
from types import ModuleType
from typing import Any

from torrcast import facts_fetch as _fetch
from torrcast import facts_origin as _origin
from torrcast.facts_fetch import (
    BLURB_CAP,
    HTTP_TIMEOUT,
    TYPE_CHECKING,
    Facts,
    Path,
    _about_cinema,
    _article,
    _cache_path,
    _cached,
    _cached_origin,
    _crowded,
    _ends_phrase,
    _extract_params,
    _fits_type,
    _key,
    _localized_short_name,
    _origin_key,
    _other_part,
    _pages,
    _ranked,
    _read_cache,
    _read_pages,
    _remember,
    _remember_origin,
    _same_latin,
    _search_params,
    _write_cache,
    akin,
    english_title,
    fetch,
    json,
    latin_title,
    namesake,
    picture_year,
    ratings,
    re,
    read_origin,
    read_sparql,
    same_words,
    sentence,
    shorten,
    slugify,
    split_franchise_index,
    state_path,
    threading,
    time,
    transliterate,
    wiki_extracts,
    wikidata_ids,
)
from torrcast.facts_origin import (
    _ABBREV,
    _CINEMA_RE,
    _CJK,
    _CYRILLIC,
    _DEFAULT_CACHE_PATH,
    _EXCHARS,
    _EXLIMIT,
    _FILM_WORD_RE,
    _GENRE_RE,
    _HATNOTE_RE,
    _LAST_WORD_RE,
    _MADE_RE,
    _NEAR_LETTERS,
    _ODD_WEIGHT,
    _ORIGINAL_RE,
    _PHRASE_WORDS,
    _QUALIFIERS,
    _RESOLVE_LOCK,
    _RESOLVE_TTL,
    _RESOLVED,
    _RU_LOCK,
    _RU_NAMES,
    _RUNTIME_RE,
    _SCREEN_RE,
    _SEARCH_HITS,
    _SENTENCE_START_RE,
    _SERIES_WORD_RE,
    _SUGGEST_HITS,
    _TAIL_RE,
    _TITLED_RE,
    _TV_KINDS,
    _VOTES,
    _WIKI_HOST,
    _WIKI_PATH,
    _WIKIDATA_HOST,
    _WIKIDATA_PATH,
    _WORK_RE,
    _YEAR_RE,
    CACHE_PATH,
    EMPTY_TTL,
    FACTS_BUDGET,
    RATINGS_PATH,
    RU_NAMES_PATH,
    SOURCE_JOIN,
    SOURCE_MAP,
    SOURCE_WIKI,
    SOURCE_WIKIDATA,
    TOPUP_LIMIT,
    USER_AGENT,
    Fact,
    Final,
    Origin,
    _asked_otherwise,
    _by_phrase,
    _catalogued,
    _digit_edit,
    _imdb_ru,
    _IPv4Connection,
    _misremembered,
    _near_name,
    _one_edit,
    _origin_typed,
    _outweighed,
    _own_name_first,
    _read_ru_names,
    _resolve,
    _ru_names,
    _RuName,
    _same_picture_origin,
    _second_source_year,
    _suggested,
    _votes,
    confirmed_year,
    confirms,
    contextlib,
    dataclass,
    get_json,
    hms,
    http,
    minutes_of,
    origin,
    origin_either,
    origin_now,
    os,
    published_year,
    read_published,
    redirected_name,
    same_name,
    same_word,
    socket,
    sourced,
    ssl,
    titles_for,
    urlencode,
    with_source,
    without_source,
)

_PARTS = (_origin, _fetch)
_namespace: dict[str, Any] = {}
for _part in _PARTS:
    _namespace.update(
        (name, value) for name, value in vars(_part).items() if not name.startswith("__")
    )
globals().update(_namespace)
for _part in _PARTS:
    vars(_part).update(_namespace)


class _FactsModule(ModuleType):
    def __setattr__(self, name: str, value: Any) -> None:
        super().__setattr__(name, value)
        if not name.startswith("__"):
            for part in _PARTS:
                if name in vars(part):
                    setattr(part, name, value)


sys.modules[__name__].__class__ = _FactsModule
__all__ = [name for name in globals() if not name.startswith("_")]
