"""Совместимый фасад разбора имён раздач."""

from __future__ import annotations

from torrcast.domain._name_data import (
    _ALTERNATIVE_PICTURE_RE,
    _ALTERNATIVE_TITLE_RE,
    _ANIME_INDEXERS,
    _ANIME_RE,
    _AV1_RE,
    _AVI_RE,
    _BRACKETS_RE,
    _CHANNEL_RE,
    _CHAPTER_RE,
    _CODEC_TOKEN_RE,
    _COLLECTION_CUT_RE,
    _COLLECTION_LATIN,
    _COLLECTION_RUSSIAN,
    _CYRILLIC,
    _DUBBED,
    _ENDING,
    _EPISODE_BRACKET_RE,
    _EPISODE_COUNT_RE,
    _EPISODE_ONLY_RES,
    _EPISODE_SPAN_RES,
    _EXTRAS_RE,
    _EXTRAS_SURE_RE,
    _FANSUB_EPISODE_RE,
    _FOREIGN_DUB_RE,
    _FOREIGN_LANG,
    _FRANCHISE_MIN,
    _GLUE,
    _H264_RE,
    _HD_SOURCES,
    _HDR_RE,
    _HEVC_RE,
    _JUNK_RE,
    _LATIN,
    _LAYOUT,
    _MERGED_TAIL,
    _MPEG4_RE,
    _NON_VIDEO_RE,
    _NUMERALS,
    _NUMERO_RE,
    _OPEN_BRACKET_RE,
    _PART_NUMBER_RE,
    _QUALITY_RE,
    _ROMAN,
    _RU_AUDIO_RE,
    _RU_CUT_WORDS,
    _RU_EXT_RE,
    _RU_STUDIO_RE,
    _SD_SOURCES,
    _SEASON_EPISODE_RES,
    _SEASON_ONLY_RES,
    _SEASON_SPAN_RES,
    _SERIES_HINT_RE,
    _SMALL_RATIO,
    _SOURCES,
    _SPELL_X,
    _STEM,
    _STEREO_LAYOUT_RE,
    _STEREO_RE,
    _SUB_MENTION_RE,
    _TAG_ONLY_RE,
    _TAG_VOICES,
    _TECH_TOKEN_RE,
    _TITLE_CUT_RE,
    _TITLE_NUMBER_RE,
    _TITLE_TAIL_RE,
    _TRANSLIT,
    _TWO_D_RE,
    _UKRAINIAN,
    _VIDEO_MARKER_RE,
    _VOICES,
    _WITH_EXTRAS_RE,
    _YEAR_PATTERNS,
    THIN_POOL,
    VIDEO_EXT,
)
from torrcast.domain.akin import _akin
from torrcast.domain.alt_query import alt_query
from torrcast.domain.anime_indexer import anime_indexer
from torrcast.domain.episode import Episode
from torrcast.domain.franchise_key import franchise_key
from torrcast.domain.franchise_name import franchise_name
from torrcast.domain.in_digits import in_digits
from torrcast.domain.kind import Kind
from torrcast.domain.looks_anime import looks_anime
from torrcast.domain.paired import _paired
from torrcast.domain.part_number import part_number
from torrcast.domain.picture import Picture
from torrcast.domain.release import Release
from torrcast.domain.same_word import same_word
from torrcast.domain.same_words import same_words
from torrcast.domain.slugify import slugify
from torrcast.domain.spell import spell
from torrcast.domain.split_franchise_index import split_franchise_index
from torrcast.domain.transliterate import transliterate
from torrcast.domain.unbranded import _unbranded
from torrcast.domain.unswap_layout import unswap_layout
from torrcast.domain.wire_query import wire_query

__all__ = [
    "THIN_POOL",
    "VIDEO_EXT",
    "_ALTERNATIVE_PICTURE_RE",
    "_ALTERNATIVE_TITLE_RE",
    "_ANIME_INDEXERS",
    "_ANIME_RE",
    "_AV1_RE",
    "_AVI_RE",
    "_BRACKETS_RE",
    "_CHANNEL_RE",
    "_CHAPTER_RE",
    "_CODEC_TOKEN_RE",
    "_COLLECTION_CUT_RE",
    "_COLLECTION_LATIN",
    "_COLLECTION_RUSSIAN",
    "_CYRILLIC",
    "_DUBBED",
    "_ENDING",
    "_EPISODE_BRACKET_RE",
    "_EPISODE_COUNT_RE",
    "_EPISODE_ONLY_RES",
    "_EPISODE_SPAN_RES",
    "_EXTRAS_RE",
    "_EXTRAS_SURE_RE",
    "_FANSUB_EPISODE_RE",
    "_FOREIGN_DUB_RE",
    "_FOREIGN_LANG",
    "_FRANCHISE_MIN",
    "_GLUE",
    "_H264_RE",
    "_HDR_RE",
    "_HD_SOURCES",
    "_HEVC_RE",
    "_JUNK_RE",
    "_LATIN",
    "_LAYOUT",
    "_MERGED_TAIL",
    "_MPEG4_RE",
    "_NON_VIDEO_RE",
    "_NUMERALS",
    "_NUMERO_RE",
    "_OPEN_BRACKET_RE",
    "_PART_NUMBER_RE",
    "_QUALITY_RE",
    "_ROMAN",
    "_RU_AUDIO_RE",
    "_RU_CUT_WORDS",
    "_RU_EXT_RE",
    "_RU_STUDIO_RE",
    "_SD_SOURCES",
    "_SEASON_EPISODE_RES",
    "_SEASON_ONLY_RES",
    "_SEASON_SPAN_RES",
    "_SERIES_HINT_RE",
    "_SMALL_RATIO",
    "_SOURCES",
    "_SPELL_X",
    "_STEM",
    "_STEREO_LAYOUT_RE",
    "_STEREO_RE",
    "_SUB_MENTION_RE",
    "_TAG_ONLY_RE",
    "_TAG_VOICES",
    "_TECH_TOKEN_RE",
    "_TITLE_CUT_RE",
    "_TITLE_NUMBER_RE",
    "_TITLE_TAIL_RE",
    "_TRANSLIT",
    "_TWO_D_RE",
    "_UKRAINIAN",
    "_VIDEO_MARKER_RE",
    "_VOICES",
    "_WITH_EXTRAS_RE",
    "_YEAR_PATTERNS",
    "Episode",
    "Kind",
    "Picture",
    "Release",
    "_akin",
    "_paired",
    "_unbranded",
    "alt_query",
    "anime_indexer",
    "franchise_key",
    "franchise_name",
    "in_digits",
    "looks_anime",
    "part_number",
    "same_word",
    "same_words",
    "slugify",
    "spell",
    "split_franchise_index",
    "transliterate",
    "unswap_layout",
    "wire_query",
]
