"""Совместимый фасад разбора имён, эпизодов и франшиз."""

from __future__ import annotations

# Статический список реэкспортов: и mypy, и человек читают его, а не собранный на лету.
__all__ = [
    "THIN_POOL",
    "VIDEO_EXT",
    "_EXTRAS_RE",
    "Episode",
    "EpisodeFile",
    "Kind",
    "Picture",
    "Release",
    "_both_languages",
    "_numbered_line",
    "alt_query",
    "anime_indexer",
    "by_majority",
    "catalog_has_name",
    "cluster",
    "franchise_key",
    "franchise_name",
    "franchises",
    "glue",
    "in_digits",
    "looks_anime",
    "map_episodes",
    "menu_order",
    "other_words",
    "outside_numbering",
    "parse_episode",
    "parse_release_name",
    "part_number",
    "pick_franchise",
    "reads_season",
    "same_word",
    "same_words",
    "seasons_named",
    "slugify",
    "spell",
    "split_episode",
    "split_franchise_index",
    "transliterate",
    "unswap_layout",
    "wire_query",
]

from torrcast.catalog import (
    _both_languages,
    catalog_has_name,
    pick_franchise,
    reads_season,
)
from torrcast.episodes import (
    EpisodeFile,
    map_episodes,
    parse_episode,
    parse_release_name,
    split_episode,
)
from torrcast.franchise import (
    _numbered_line,
    by_majority,
    cluster,
    franchises,
    glue,
    menu_order,
    other_words,
    outside_numbering,
    seasons_named,
)
from torrcast.parse_name import (
    _EXTRAS_RE,
    THIN_POOL,
    VIDEO_EXT,
    Episode,
    Kind,
    Picture,
    Release,
    alt_query,
    anime_indexer,
    franchise_key,
    franchise_name,
    in_digits,
    looks_anime,
    part_number,
    same_word,
    same_words,
    slugify,
    spell,
    split_franchise_index,
    transliterate,
    unswap_layout,
    wire_query,
)
