"""Совместимый фасад моделей и правил отбора для старых импортов."""

# mypy: ignore-errors
import sys

from torrcast import trace as trace
from torrcast.usecases import select as _selection_impl
from torrcast.usecases.select import (
    CAUTIOUS,
    COPY,
    EXIT_OK,
    META_BUDGET,
    PROBE_BUDGET,
    RECODE_HEIGHT,
    REFUSE,
    Config,
    Entry,
    Episode,
    EpisodeFile,
    InfraError,
    Media,
    NotFoundError,
    Picture,
    Profile,
    Progress,
    Release,
    ServerDownError,
    SwarmError,
    TorrcastError,
    TorrFile,
    WatchState,
    _about,
    _Bench,
    _continue,
    _did_not_answer,
    _nothing_late,
    _Plan,
    _Prep,
    _remembered,
    _revoice,
    _Series,
    _silenced,
    _turned_down,
    _Voiced,
    _voiced,
    _waiting_note,
    field,
    map_episodes,
    recode_note,
)

__all__ = [
    "CAUTIOUS",
    "COPY",
    "EXIT_OK",
    "META_BUDGET",
    "PROBE_BUDGET",
    "RECODE_HEIGHT",
    "REFUSE",
    "Config",
    "Entry",
    "Episode",
    "EpisodeFile",
    "InfraError",
    "Media",
    "NotFoundError",
    "Picture",
    "Profile",
    "Progress",
    "Release",
    "ServerDownError",
    "SwarmError",
    "TorrcastError",
    "TorrFile",
    "WatchState",
    "_Bench",
    "_Plan",
    "_Prep",
    "_Series",
    "_Voiced",
    "_about",
    "_continue",
    "_did_not_answer",
    "_nothing_late",
    "_remembered",
    "_revoice",
    "_silenced",
    "_turned_down",
    "_voiced",
    "_waiting_note",
    "field",
    "map_episodes",
    "recode_note",
    "trace",
]

sys.modules[__name__] = _selection_impl
