"""Внешние решения и ввод-вывод сценария выбора."""

from typing import Any, Protocol


class ChoiceEnvironment(Protocol):
    """Всё, что выбор получает от композиционного корня."""

    @property
    def alive_seeders(self) -> int: ...
    @property
    def ctl_env(self) -> str: ...
    @property
    def not_found_error(self) -> type[Exception]: ...

    def read_command(self) -> str | None: ...
    def write(self, line: str) -> None: ...
    def stdin_is_tty(self) -> bool: ...
    def ask(self, question: str, count: int, default: int | None = 1) -> int: ...
    def columns(self) -> int: ...
    def fact(self) -> Any: ...
    def empty_origin(self) -> Any: ...
    def origin(self, title: str, series: bool) -> Any: ...
    def shorten(self, text: str) -> str: ...
    def emit(self, event: str, action: str, **facts: object) -> None: ...
    def cut(self, text: str, limit: int) -> str: ...
    def bitrate_of(self, release: Any, duration: float) -> float | None: ...
    def hevc_hope(self, release: Any, last: bool) -> bool: ...
    def is_candidate(self, release: Any, *args: Any, **kwargs: Any) -> bool: ...
    def is_dated(self, release: Any, runtime: float) -> bool: ...
    def timed(self, *args: Any) -> Any: ...
