"""Даёт сценариям монотонное время, стенные часы и ожидание."""

from typing import Protocol


class Clock(Protocol):
    def monotonic(self) -> float: ...
    def wall(self) -> float: ...
    def sleep(self, seconds: float) -> None: ...
