"""Даёт сценариям ввод и вывод через консоль."""

from typing import Protocol


class Console(Protocol):
    def ask(self, question: str, default: str = "") -> str: ...
    #: Дефолтом отвечает пустой Enter, и номер у него свой у каждого вопроса: меню
    #: озвучек предлагает ту дорожку, которую отбор и так возьмёт, а не первую строку.
    def choose(self, question: str, count: int, default: int = 1) -> int: ...
    def interactive(self) -> bool: ...
    def write(self, message: str) -> None: ...
