"""Окружение самопроверки: всё, что ``cast doctor`` узнаёт снаружи себя.

Порт делит каждую пробу надвое: КАК УЗНАТЬ живёт тут и в адаптере, а ЧТО СЧИТАЕТСЯ
ЗДОРОВЫМ - в правилах домена. Зовёт сценарий :mod:`torrcast.usecases.doctor`.
"""

from typing import Protocol

from torrcast.ports.health_config import HealthConfig


class HealthEnvironment(Protocol):
    """Подпроцессы, сеть, диск и часы, которыми сценарий сам не владеет."""

    # Консоль и локаль.
    def has_terminal(self) -> bool: ...
    def terminal_utf8(self) -> bool | None: ...
    def encoding(self) -> str: ...
    def locale_env(self) -> str: ...

    # Внешние программы.
    def ffmpeg_help(self) -> str | None: ...
    def ffmpeg_version(self) -> str | None: ...
    def prowlarr_unit(self, timeout: float) -> str | None: ...

    # Поиск.
    def get_json(self, url: str, headers: dict[str, str], timeout: float) -> object | None: ...
    def search_titles(
        self, url: str, apikey: str, indexer: int, query: str, timeout: float
    ) -> list[str] | None: ...

    # Раздача торрента.
    def torrserver_echo(self, url: str, timeout: float) -> str | None: ...
    def torrserver_settings(self, url: str, timeout: float) -> object | None: ...

    # Машина.
    def machine_memory(self) -> int: ...
    def disk_free(self, path: str) -> int: ...

    # Приёмник.
    def cast_port(self) -> int: ...
    def our_address(self, tv: str) -> str: ...
    def port_error(self, host: str, port: int, timeout: float) -> str: ...
    def heard_receivers(self) -> tuple[list[str], str, str]: ...
    def receiver_profile(self, config: HealthConfig) -> tuple[str, str, bool]: ...

    # Раздача HLS и диагностика.
    def hls_base(self, config: HealthConfig) -> tuple[str, str]: ...
    def cert_days(self, path: str) -> int | None: ...
    def shelves(self) -> tuple[str, tuple[int, int], tuple[int, int]]: ...
    def shelf_limits(self) -> tuple[int, int]: ...
    def trace_health(self) -> tuple[bool, float, int]: ...
    def trace_dir(self) -> str: ...
    def retain_days(self) -> int: ...
    def now(self) -> float: ...
