"""Даёт командам stop и status состояние внешнего сеанса показа."""

from typing import Protocol

from torrcast.domain.playback_snapshot import PlaybackSnapshot


class PlaybackSession(Protocol):
    def active(self) -> bool: ...
    def key(self) -> str: ...
    def stop(self) -> None: ...
    def snapshot(self, key: str = "") -> PlaybackSnapshot | None: ...
    def release(self, torrent_hash: str) -> None: ...
    def cache_reserve(self, snapshot: PlaybackSnapshot) -> str: ...
    def stream_address(self) -> str: ...
    def receiver_name(self) -> str: ...
