"""Даёт сценариям метаданные торрента и доступ к потоку байтов."""

from typing import Protocol

from torrcast.domain.torr_file import TorrFile


class TorrentEngine(Protocol):
    def add(self, magnet: str) -> str: ...
    def files(self, torrent_hash: str) -> list[TorrFile]: ...
    def stream_url(self, torrent_hash: str, index: int) -> str: ...
    def remove(self, torrent_hash: str) -> bool: ...
