"""Среда прогрева: часы, файловая операция и телеметрия."""

from collections.abc import Callable
from typing import Protocol


class WarmGrid(Protocol):
    """Сетка сегментов в объёме, который нужен прогреву."""

    @property
    def count(self) -> int: ...
    @property
    def duration(self) -> float: ...
    @property
    def origin(self) -> float: ...
    @property
    def on_keys(self) -> bool: ...
    @property
    def weigh(self) -> Callable[[float, float], float] | None: ...

    def start(self, slot: int) -> float: ...
    def end(self, slot: int) -> float: ...
    def span(self, slot: int) -> float: ...


class WarmEnvironment(Protocol):
    """Побочные эффекты, которыми сценарий прогрева сам не владеет."""

    def epoch(self) -> float: ...

    def monotonic(self) -> float: ...

    def sleep(self, seconds: float) -> None: ...

    def remove_tree(self, path: object) -> None: ...

    def emit(self, event: str, *args: object, **facts: object) -> None: ...

    def mark(self, name: str, **facts: object) -> None: ...

    def segment_name(self, slot: int) -> str: ...
    def segment_slot(self, name: str) -> int: ...
    def hms(self, seconds: float) -> str: ...
    @property
    def packer_type(self) -> object: ...
    def pack_command(self, *args: object, **kwargs: object) -> object: ...
    def pack_start(self, *args: object, **kwargs: object) -> object: ...

    audio_mbit: float
    max_segment_bytes: int
    ts_overhead: float
